# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Episode.create([
  { season: 1, episode_number: 1,  title: 'The Crawling Eye' }, 
  { season: 1, episode_number: 2,  title: 'The Robot vs. The Aztec Mummy' }, 
  { season: 1, episode_number: 3,  title: 'The Mad Monster' }, 
  { season: 1, episode_number: 4,  title: 'Women of the Prehistoric Planet' }, 
  { season: 1, episode_number: 5,  title: 'The Corpse Vanishes' }, 
  { season: 1, episode_number: 6,  title: 'The Crawling Hand' }, 
  { season: 1, episode_number: 7,  title: 'Robot Monster' }, 
  { season: 1, episode_number: 8,  title: 'The Slime People' }, 
  { season: 1, episode_number: 9,  title: 'Project Moon Base' }, 
  { season: 1, episode_number: 10, title: 'Robot Holocaust' }, 
  { season: 1, episode_number: 11, title: 'Moon Zero Two' }, 
  { season: 1, episode_number: 12, title: 'Untamed Youth' }, 
  { season: 1, episode_number: 13, title: 'The Black Scorpion' }, 

  { season: 2, episode_number: 1,  title: 'Rocketship X-M' }, 
  { season: 2, episode_number: 2,  title: 'The Sidehackers' }, 
  { season: 2, episode_number: 3,  title: 'Jungle Goddess' }, 
  { season: 2, episode_number: 4,  title: 'Catalina Caper' }, 
  { season: 2, episode_number: 5,  title: 'Rocket Attack USA' }, 
  { season: 2, episode_number: 6,  title: 'Ring of Terror' }, 
  { season: 2, episode_number: 7,  title: 'Wild Rebels' }, 
  { season: 2, episode_number: 8,  title: 'Lost Continent' }, 
  { season: 2, episode_number: 9,  title: 'The Hellcats' }, 
  { season: 2, episode_number: 10, title: 'King Dinosaur' }, 
  { season: 2, episode_number: 11, title: 'First Spaceship on Venus' }, 
  { season: 2, episode_number: 12, title: 'Godzilla vs. Megalon' }, 
  { season: 2, episode_number: 13, title: 'Godzilla vs. the Sea Monster' }, 

  { season: 3, episode_number: 1,  title: 'Cave Dwellers' }, 
  { season: 3, episode_number: 2,  title: 'Gamera' }, 
  { season: 3, episode_number: 3,  title: 'Pod People' }, 
  { season: 3, episode_number: 4,  title: 'Gamera vs. Barugon' }, 
  { season: 3, episode_number: 5,  title: 'Stranded in Space' }, 
  { season: 3, episode_number: 6,  title: 'Time of the Apes' }, 
  { season: 3, episode_number: 7,  title: 'Daddy-O' }, 
  { season: 3, episode_number: 8,  title: 'Gamera vs. Gaos' }, 
  { season: 3, episode_number: 9,  title: 'The Amazing Colossal Man' }, 
  { season: 3, episode_number: 10, title: 'Fugitive Alien' }, 
  { season: 3, episode_number: 11, title: 'It Conquered the World' }, 
  { season: 3, episode_number: 12, title: 'Gamera vs. Guiron' }, 
  { season: 3, episode_number: 13, title: 'Earth vs. the Spider' }, 
  { season: 3, episode_number: 14, title: 'Mighty Jack' }, 
  { season: 3, episode_number: 15, title: 'Teenage Cave Man' }, 
  { season: 3, episode_number: 16, title: 'Gamera vs. Zigra' }, 
  { season: 3, episode_number: 17, title: 'Viking Women and the Sea Serpent' }, 
  { season: 3, episode_number: 18, title: 'Star Force: Fugitive Alien II' }, 
  { season: 3, episode_number: 19, title: 'War of the Colossal Beast' }, 
  { season: 3, episode_number: 20, title: 'The Unearthly' }, 
  { season: 3, episode_number: 21, title: 'Santa Claus Conquers the Martians' }, 
  { season: 3, episode_number: 22, title: 'Master Ninja I' }, 
  { season: 3, episode_number: 23, title: 'The Castle of Fu Manchu' }, 
  { season: 3, episode_number: 24, title: 'Master Ninja II' }, 

  { season: 4, episode_number: 1,  title: 'Space Travelers' }, 
  { season: 4, episode_number: 2,  title: 'The Giant Gila Monster' }, 
  { season: 4, episode_number: 3,  title: 'City Limits' }, 
  { season: 4, episode_number: 4,  title: 'Teenagers from Outer Space' }, 
  { season: 4, episode_number: 5,  title: 'Being from Another Planet' }, 
  { season: 4, episode_number: 6,  title: 'Attack of the Giant Leeches' }, 
  { season: 4, episode_number: 7,  title: 'The Killer Shrews' }, 
  { season: 4, episode_number: 8,  title: 'Hercules Unchained' }, 
  { season: 4, episode_number: 9,  title: 'Indestructible Man' }, 
  { season: 4, episode_number: 10, title: 'Hercules Against the Moon Men' }, 
  { season: 4, episode_number: 11, title: 'The Magic Sword' }, 
  { season: 4, episode_number: 12, title: 'Hercules and the Captive Women' }, 
  { season: 4, episode_number: 13, title: 'Manhunt in Space' }, 
  { season: 4, episode_number: 14, title: 'Tormented' }, 
  { season: 4, episode_number: 15, title: 'The Beatniks' }, 
  { season: 4, episode_number: 16, title: 'Fire Maidens of Outer Space' }, 
  { season: 4, episode_number: 17, title: 'Crash of the Moons' }, 
  { season: 4, episode_number: 18, title: 'Attack of the Eye Creatures' }, 
  { season: 4, episode_number: 19, title: 'The Rebel Set' }, 
  { season: 4, episode_number: 20, title: 'The Human Duplicators' }, 
  { season: 4, episode_number: 21, title: 'Monster a Go-Go' }, 
  { season: 4, episode_number: 22, title: 'The Day the Earth Froze' }, 
  { season: 4, episode_number: 23, title: 'Bride of the Monster' }, 
  { season: 4, episode_number: 24, title: 'Manos: The Hands of Fate' }, 

  { season: 5, episode_number: 1,  title: 'Warrior of the Lost World' }, 
  { season: 5, episode_number: 2,  title: 'Hercules' }, 
  { season: 5, episode_number: 3,  title: 'Swamp Diamonds' }, 
  { season: 5, episode_number: 4,  title: 'Secret Agent Super Dragon' }, 
  { season: 5, episode_number: 5,  title: 'The Magic Voyage of Sinbad' }, 
  { season: 5, episode_number: 6,  title: 'Eegah' }, 
  { season: 5, episode_number: 7,  title: 'I Accuse My Parents' }, 
  { season: 5, episode_number: 8,  title: 'Operation Double 007' }, 
  { season: 5, episode_number: 9,  title: "The Girl in Lovers' Lane" }, 
  { season: 5, episode_number: 10, title: 'The Painted Hills' }, 
  { season: 5, episode_number: 11, title: 'Gunslinger' }, 
  { season: 5, episode_number: 12, title: 'Mitchell' }, 
  { season: 5, episode_number: 13, title: "The Brain That Wouldn't Die" }, 
  { season: 5, episode_number: 14, title: 'Teenage Strangler' }, 
  { season: 5, episode_number: 15, title: 'The Wild Wild World of Batwoman' }, 
  { season: 5, episode_number: 16, title: 'Alien from L.A.' }, 
  { season: 5, episode_number: 17, title: 'Beginning of the End' }, 
  { season: 5, episode_number: 18, title: 'The Atomic Brain' }, 
  { season: 5, episode_number: 19, title: 'Outlaw of Gor' }, 
  { season: 5, episode_number: 20, title: 'Radar Secret Service' }, 
  { season: 5, episode_number: 21, title: 'Santa Claus' }, 
  { season: 5, episode_number: 22, title: 'Teenage Crime Wave' }, 
  { season: 5, episode_number: 23, title: 'Village of the Giants' }, 
  { season: 5, episode_number: 24, title: '12 to the Moon' }, 

  { season: 6, episode_number: 1,  title: 'Girls Town' }, 
  { season: 6, episode_number: 2,  title: 'Invasion USA' }, 
  { season: 6, episode_number: 3,  title: 'The Dead Talk Back' }, 
  { season: 6, episode_number: 4,  title: 'Zombie Nightmare' }, 
  { season: 6, episode_number: 5,  title: 'Colossus and the Headhunters' }, 
  { season: 6, episode_number: 6,  title: 'The Creeping Terror' }, 
  { season: 6, episode_number: 7,  title: 'Bloodlust!' }, 
  { season: 6, episode_number: 8,  title: 'Code Name: Diamond Head' }, 
  { season: 6, episode_number: 9,  title: 'The Skydivers' }, 
  { season: 6, episode_number: 10, title: 'The Violent Years' }, 
  { season: 6, episode_number: 11, title: 'Last of the Wild Horses' }, 
  { season: 6, episode_number: 12, title: 'The Starfighters' }, 
  { season: 6, episode_number: 13, title: 'The Sinister Urge' }, 
  { season: 6, episode_number: 14, title: 'San Francisco International' }, 
  { season: 6, episode_number: 15, title: 'Kitten with a Whip' }, 
  { season: 6, episode_number: 16, title: 'Racket Girls' }, 
  { season: 6, episode_number: 17, title: 'The Sword and the Dragon' }, 
  { season: 6, episode_number: 18, title: 'High School Big Shot' }, 
  { season: 6, episode_number: 19, title: 'Red Zone Cuba' }, 
  { season: 6, episode_number: 20, title: 'Danger!! Death Ray' }, 
  { season: 6, episode_number: 21, title: 'The Beast of Yucca Flats' }, 
  { season: 6, episode_number: 22, title: 'Angels Revenge' }, 
  { season: 6, episode_number: 23, title: 'The Amazing Transparent Man' }, 
  { season: 6, episode_number: 24, title: 'Samson vs. the Vampire Women' }, 

  { season: 7, episode_number: 1,  title: 'Night of the Blood Beast' }, 
  { season: 7, episode_number: 2,  title: 'The Brute Man' }, 
  { season: 7, episode_number: 3,  title: 'Deathstalker and the Warriors from Hell' }, 
  { season: 7, episode_number: 4,  title: 'The Incredible Melting Man' }, 
  { season: 7, episode_number: 5,  title: 'Escape 2000' }, 
  { season: 7, episode_number: 6,  title: 'Laserblast' }, 

  { season: 8, episode_number: 1,  title: 'Revenge of the Creature' }, 
  { season: 8, episode_number: 2,  title: 'The Leech Woman' }, 
  { season: 8, episode_number: 3,  title: 'The Mole People' }, 
  { season: 8, episode_number: 4,  title: 'The Deadly Mantis' }, 
  { season: 8, episode_number: 5,  title: "The Thing That Couldn't Die" }, 
  { season: 8, episode_number: 6,  title: 'The Undead' }, 
  { season: 8, episode_number: 7,  title: 'Terror from the Year 5000' }, 
  { season: 8, episode_number: 8,  title: 'The She Creature' }, 
  { season: 8, episode_number: 9,  title: 'I Was a Teenage Werewolf' }, 
  { season: 8, episode_number: 10, title: 'The Giant Spider Invasion' }, 
  { season: 8, episode_number: 11, title: 'Parts: The Clonus Horror' }, 
  { season: 8, episode_number: 12, title: 'The Incredibly Strange Creatures Who Stopped Living and Became Mixed-Up Zombies' }, 
  { season: 8, episode_number: 13, title: 'Jack Frost' }, 
  { season: 8, episode_number: 14, title: 'Riding with Death' }, 
  { season: 8, episode_number: 15, title: 'Agent for H.A.R.M.' }, 
  { season: 8, episode_number: 16, title: 'Prince of Space' }, 
  { season: 8, episode_number: 17, title: 'The Horror of Party Beach' }, 
  { season: 8, episode_number: 18, title: 'Devil Doll' }, 
  { season: 8, episode_number: 19, title: 'Invasion of the Neptune Men' }, 
  { season: 8, episode_number: 20, title: 'Space Mutiny' }, 
  { season: 8, episode_number: 21, title: 'Time Chasers' }, 
  { season: 8, episode_number: 22, title: 'Overdrawn at the Memory Bank' }, 

  { season: 9, episode_number: 1,  title: 'The Projected Man' }, 
  { season: 9, episode_number: 2,  title: 'The Phantom Planet' }, 
  { season: 9, episode_number: 3,  title: 'The Pumaman' }, 
  { season: 9, episode_number: 4,  title: 'Werewolf' }, 
  { season: 9, episode_number: 5,  title: 'The Deadly Bees' }, 
  { season: 9, episode_number: 6,  title: 'The Space Children' }, 
  { season: 9, episode_number: 7,  title: 'Hobgoblins' }, 
  { season: 9, episode_number: 8,  title: 'The Touch of Satan' }, 
  { season: 9, episode_number: 9,  title: 'Gorgo' }, 
  { season: 9, episode_number: 10, title: 'The Final Sacrifice' }, 
  { season: 9, episode_number: 11, title: 'Devil Fish' }, 
  { season: 9, episode_number: 12, title: 'The Screaming Skull' }, 
  { season: 9, episode_number: 13, title: 'Quest of the Delta Knights' }, 

  { season: 10, episode_number: 1,  title: 'Soultaker' }, 
  { season: 10, episode_number: 2,  title: 'Girl in Gold Boots' }, 
  { season: 10, episode_number: 3,  title: "Merlin's Shop of Mystical Wonders" }, 
  { season: 10, episode_number: 4,  title: 'Future War' }, 
  { season: 10, episode_number: 5,  title: 'Blood Waters of Dr. Z' }, 
  { season: 10, episode_number: 6,  title: 'Boggy Creek II: And The Legend Continues' }, 
  { season: 10, episode_number: 7,  title: 'Track of the Moon Beast' }, 
  { season: 10, episode_number: 8,  title: 'Final Justice' }, 
  { season: 10, episode_number: 9,  title: 'Hamlet' }, 
  { season: 10, episode_number: 10, title: 'It Lives By Night' }, 
  { season: 10, episode_number: 11, title: 'Horrors of Spider Island' }, 
  { season: 10, episode_number: 12, title: 'Squirm' }, 
  { season: 10, episode_number: 13, title: 'Diabolik' }
  
])
